name: Automated Python Project Version Bump
description: Automated Python Project version bump, only recommend to run in PRs.

inputs:
  pyproject-file:
    description: "pyproject toml file, only relevant for buildType python"
    default: "pyproject.toml"
    required: false
  bump-command:
    description: "Command to update the version"
    default: "poetry version @NEW_VERSION@"
    required: false
  commit-message:
    description: "Custom commit message for version bump commit"
    default: "version bump to"
    required: false
  git-username:
    description: "Git username for the commit"
    default: "github-actions[bot]"
    required: false
  git-useremail:
    description: "Git user email for the commit"
    default: "github-actions[bot]@users.noreply.github.com"
    required: false
  post-command:
    description: "shell command to run after version bump"
    default: ""
    required: false
  token:
    description: "Github token with permission to fetch PR status and commit the changes"
    required: true
  dry-run:
    description: "If true, skip git push"
    default: "false"
    required: false

outputs:
  bumped:
    description: "True if version was bumped"
    value: ${{ steps.bump.outputs.bumped }}
  new-version:
    description: "The new version"
    value: ${{ steps.bump.outputs.new-version }}

runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v6
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install poetry
      shell: bash
      run: |
        pip install poetry toml-cli

    - name: Bump up project version
      id: bump
      uses: ./.github/actions/core
      with:
        build-type: "python"
        pyproject-file: ${{ inputs.pyproject-file }}
        git-username: ${{ inputs.git-username }}
        git-useremail: ${{ inputs.git-useremail }}
        commit-message: ${{ inputs.commit-message }}
        token: ${{ inputs.token }}
        bump-command: ${{ inputs.bump-command }}
        post-command: ${{ inputs.post-command }}
        dry-run: ${{ inputs.dry-run }}
