name: Automated Maven Project Version Bump
description: Automated Maven Version Bump, only recommend to run in PRs.

inputs:
  pom-file:
    description: "Where to find the pom file"
    default: "pom.xml"
    required: false
  bump-command:
    description: "Command to update the version"
    default: "mvn org.codehaus.mojo:versions-maven-plugin:set -DnewVersion=@NEW_VERSION@ -s settings.xml"
    required: false
  commit-message:
    description: "Custom commit message for version bump commit"
    default: "version bump to"
    required: false
  version-property-path:
    description: "Version property to update"
    default: '["project","version"]'
    required: false
  git-username:
    description: "Git username for the commit"
    default: "github-actions[bot]"
    required: false
  git-useremail:
    description: "Git user email for the commit"
    default: "github-actions[bot]@users.noreply.github.com"
    required: false
  post-command:
    description: "shell command to run after version bump"
    default: ""
    required: false
  token:
    description: "Github token with permission to fetch PR status and commit the changes"
    required: true
  dry-run:
    description: "If true, skip git push"
    default: "false"
    required: false

outputs:
  bumped:
    description: "True if version was bumped"
    value: ${{ steps.bump.outputs.bumped }}
  new-version:
    description: "The new version"
    value: ${{ steps.bump.outputs.new-version }}

runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v6
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0

    - name: Bump up project version
      id: bump
      uses: ./.github/actions/core
      with:
        build-type: "maven"
        pom-file: ${{ inputs.pom-file }}
        git-username: ${{ inputs.git-username }}
        git-useremail: ${{ inputs.git-useremail }}
        commit-message: ${{ inputs.commit-message }}
        token: ${{ inputs.token }}
        bump-command: ${{ inputs.bump-command }}
        version-property-path: ${{ inputs.version-property-path }}
        post-command: ${{ inputs.post-command }}
        dry-run: ${{ inputs.dry-run }}
