name: Automated VERSION Project Status Check
description: Automated VERSION Project status checks, only recommend to run in PRs.

inputs:
  version-file:
    description: "Where to find the version file of project, only relevant for buildType version-file"
    default: "VERSION"
    required: false
  bump-command:
    description: "Command to update the version"
    default: "echo @NEW_VERSION@ > VERSION"
    required: false
  commit-message:
    description: "Custom commit message for version bump commit"
    default: "version bump to"
    required: false
  git-username:
    description: "Git username for the commit"
    default: "github-actions[bot]"
    required: false
  git-useremail:
    description: "Git user email for the commit"
    default: "github-actions[bot]@users.noreply.github.com"
    required: false
  post-command:
    description: "shell command to run after version bump"
    default: ""
    required: false
  token:
    description: "Github token with permission to fetch PR status and commit the changes"
    required: true
  dry-run:
    description: "If true, skip git push"
    default: "false"
    required: false

outputs:
  bumped:
    description: "True if version was bumped"
    value: ${{ steps.bump.outputs.bumped }}
  new-version:
    description: "The new version"
    value: ${{ steps.bump.outputs.new-version }}

runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v6
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Bump up version file
      id: bump
      uses: ./.github/actions/core
      with:
        build-type: "version-file"
        version-file: ${{ inputs.version-file }}
        git-username: ${{ inputs.git-username }}
        git-useremail: ${{ inputs.git-useremail }}
        commit-message: ${{ inputs.commit-message }}
        token: ${{ inputs.token }}
        bump-command: ${{ inputs.bump-command }}
        post-command: ${{ inputs.post-command }}
        dry-run: ${{ inputs.dry-run }}
